import type { AppSettings } from '../../progress/storage';
import type { LocalMigrationPreview } from '../../progress/accountMigration';
import { ChevronIcon } from '../icons';

type Props = { settings: AppSettings; storageRecovery: boolean; storageWriteWarning: boolean; legacyMigrationPreview?: LocalMigrationPreview | null; onOpenSettings: () => void; onChangeParentPin: () => void; onImportLegacy?: () => void | Promise<void> };

export function DataTools({ settings, storageRecovery, storageWriteWarning, legacyMigrationPreview, onOpenSettings, onChangeParentPin, onImportLegacy }: Props) {
  return <section className="parent-card settings-status-card data-tools-card" aria-labelledby="data-tools-title"><div className="parent-card-heading data-tools-heading"><div className="data-tools-heading-copy"><span className="data-tools-heading-icon" data-data-tools-icon aria-hidden="true"><img className="data-tools-art data-tools-heading-art" src="/art/hud/settings.png" alt="" data-data-tools-art="settings" draggable={false} /></span><div><p className="eyebrow">DỮ LIỆU &amp; THIẾT BỊ</p><h2 id="data-tools-title">Cài đặt trên thiết bị</h2></div></div><span className="device-dot" aria-hidden="true" /></div>
    {(storageRecovery || storageWriteWarning) && <div className="storage-recovery-banner" role="alert"><span>{storageRecovery ? 'Dữ liệu cũ đang được giữ nguyên để phục hồi.' : 'Thay đổi cục bộ chưa ghi được; máy chủ vẫn là nguồn xác nhận.'}</span></div>}
    {legacyMigrationPreview && <div className="storage-recovery-banner" role="status"><span><strong>Dữ liệu cũ chưa gắn tài khoản.</strong> {legacyMigrationPreview.completedMissions} nhiệm vụ, {legacyMigrationPreview.stamps} dấu; chưa suy ra lịch sử.</span><button className="text-button" type="button" onClick={() => void onImportLegacy?.()}>Xem trước &amp; nhập</button></div>}
    <div className="device-list"><div className="device-row"><span className="device-row-icon" aria-hidden="true"><img className="data-tools-art data-tools-feature-art" src="/art/hud/sound.png" alt="" data-device-feature-art="sound" draggable={false} /></span><span className="device-row-label">Âm phản hồi</span><strong>{settings.sound ? 'Bật' : 'Tắt'}</strong></div><div className="device-row"><span className="device-row-icon" aria-hidden="true"><img className="data-tools-art data-tools-feature-art" src="/art/collection/collection-emblem.png" alt="" data-device-feature-art="reduced-motion" draggable={false} /></span><span className="device-row-label">Giảm chuyển động</span><strong>{settings.reducedMotion ? 'Bật' : 'Tắt'}</strong></div><button className="device-row device-row-action" type="button" onClick={onChangeParentPin}><span className="device-row-icon" aria-hidden="true"><img className="data-tools-art data-tools-action-art" src="/art/hud/parent.png" alt="" data-device-action-art="parent-pin" draggable={false} /></span><span className="device-row-label">Đổi PIN phụ huynh</span><ChevronIcon direction="right" size={19} strokeWidth={2.4} /></button></div><button className="secondary-button full-width data-tools-settings-button" type="button" onClick={onOpenSettings}><img className="data-tools-art data-tools-settings-art" src="/art/hud/settings.png" alt="" data-data-tools-art="settings-action" draggable={false} />Mở cài đặt</button>
  </section>;
}
