import type { PetId } from '../content/pets';

export type PetHomeDialogueTone = 'encouraging' | 'playful' | 'curious' | 'moody' | 'joyful' | 'serious';

export type PetHomeDialogue = {
  text: string;
  tone: PetHomeDialogueTone;
};

export const PET_HOME_DIALOGUES_BY_PET = {
  'fox-orange': [
    { text: 'Tớ có bản đồ, cậu có tò mò — cả đội sẵn sàng rồi!', tone: 'encouraging' },
    { text: 'Chậm một nhịp cũng được, tớ sẽ cùng cậu bước tiếp nhé.', tone: 'encouraging' },
    { text: 'Cậu làm tốt hơn cậu nghĩ đấy. Tớ nhìn thấy mà!', tone: 'encouraging' },
    { text: 'Tớ tin một manh mối nhỏ hôm nay có thể mở ra cả kho báu ngày mai.', tone: 'encouraging' },
    { text: 'Tớ đứng về phía cậu, kể cả lúc câu hỏi trông hơi tinh quái.', tone: 'encouraging' },
    { text: 'Nếu tớ giấu chiếc la bàn, cậu có tìm ra không nhỉ?', tone: 'playful' },
    { text: 'Suỵt… tớ vừa nghe thấy một mẩu lịch sử đang cười khúc khích.', tone: 'playful' },
    { text: 'Đuôi tớ đang quẫy theo nhịp khám phá của cậu đây!', tone: 'playful' },
    { text: 'Tớ tuyên bố hôm nay là ngày săn manh mối siêu hạng!', tone: 'playful' },
    { text: 'Cậu nhìn thấy ba lô của tớ không? Nó đang đầy ắp chuyện vui đấy.', tone: 'playful' },
    { text: 'Nếu được du hành thời gian, cậu sẽ ghé nơi nào đầu tiên?', tone: 'curious' },
    { text: 'Tớ tự hỏi lối đi này đã chứng kiến bao nhiêu câu chuyện rồi nhỉ?', tone: 'curious' },
    { text: 'Cậu thử nhìn kỹ thêm một lần nhé, chi tiết nhỏ thường rất thú vị.', tone: 'curious' },
    { text: 'La bàn chỉ về phía trước, còn trí tò mò của cậu thì chỉ khắp nơi!', tone: 'curious' },
    { text: 'Tớ muốn biết điều gì làm cậu bất ngờ nhất hôm nay.', tone: 'curious' },
    { text: 'Hôm nay tớ hơi chậm một chút, nhưng vẫn muốn đồng hành cùng cậu.', tone: 'moody' },
    { text: 'Có những ngày tớ và cậu chỉ cần hoàn thành một việc nhỏ cũng đáng tự hào rồi.', tone: 'moody' },
    { text: 'Tớ đang nghe đây. Cậu cứ suy nghĩ thật bình tĩnh nhé.', tone: 'moody' },
    { text: 'Uống một ngụm nước, thở sâu cùng tớ, rồi cậu thử lại từ từ.', tone: 'moody' },
    { text: 'Tớ cũng từng bối rối trước manh mối khó. Cậu không phải tự xoay xở đâu.', tone: 'moody' },
    { text: 'Yay! Tớ muốn nhảy một vòng quanh chiếc la bàn quá!', tone: 'joyful' },
    { text: 'Có tiến bộ rồi! Tớ và cả đội thám hiểm đang vui lây với cậu.', tone: 'joyful' },
    { text: 'Hôm nay ánh mắt cậu sáng như kho báu mới tìm thấy vậy!', tone: 'joyful' },
    { text: 'Tớ muốn lưu khoảnh khắc này vào nhật ký phiêu lưu cùng cậu!', tone: 'joyful' },
    { text: 'Tớ nghe tiếng chuông chiến thắng rồi — leng keng!', tone: 'joyful' },
    { text: 'Muốn đi xa thì cậu đọc kỹ, nghĩ kỹ và kiểm tra thật cẩn thận.', tone: 'serious' },
    { text: 'Cậu cứ suy nghĩ thật kỹ, không cần chạy đua với ai.', tone: 'serious' },
    { text: 'Tớ luôn nhớ: manh mối tốt cần một đôi mắt quan sát thật kỹ.', tone: 'serious' },
    { text: 'Nếu cậu chưa chắc, hãy quay lại tư liệu và kiểm chứng nhé.', tone: 'serious' },
    { text: 'Tớ sẽ nhắc cậu: hiểu bài quan trọng hơn trả lời thật nhanh.', tone: 'serious' },
  ],
  'elephant-blue': [
    { text: 'Tớ đi chậm cùng cậu, nhưng từng bước đều đưa cả đội xa hơn.', tone: 'encouraging' },
    { text: 'Cậu cứ yên tâm, đôi tai tớ luôn lắng nghe khi cậu cần.', tone: 'encouraging' },
    { text: 'Tớ tin sự kiên nhẫn của cậu sẽ tìm ra lối đi vững vàng.', tone: 'encouraging' },
    { text: 'Một bước nhỏ của cậu cũng làm cả hành trình thêm chắc chắn.', tone: 'encouraging' },
    { text: 'Tớ ở bên cậu; khó đến đâu, cả đội vẫn cùng nhau tiến lên.', tone: 'encouraging' },
    { text: 'Cậu nghe thấy tiếng bước chân thình thịch của tớ chưa?', tone: 'playful' },
    { text: 'Tớ giấu một tiếng phì vui trong chiếc vòi đây — cậu có đoán ra không?', tone: 'playful' },
    { text: 'Nếu đường núi biết kể chuyện, tớ sẽ ngồi nghe cùng cậu cả buổi!', tone: 'playful' },
    { text: 'Cậu đi bên trái nhé, tớ sẽ vẫy tai bên phải cho đủ nhịp!', tone: 'playful' },
    { text: 'Tớ có thể chở ba lô, còn cậu nhớ giữ nụ cười thật nhẹ nhé.', tone: 'playful' },
    { text: 'Tớ tự hỏi dấu chân này dẫn tới đâu, cậu muốn quan sát cùng tớ không?', tone: 'curious' },
    { text: 'Cậu có nghe tiếng gió đổi nhịp trên sườn núi không?', tone: 'curious' },
    { text: 'Tớ muốn ghi nhớ âm thanh này để lần sau nhận ra thật nhanh.', tone: 'curious' },
    { text: 'Chi tiết nhỏ nào vừa lọt vào mắt cậu? Tớ đang lắng nghe đây.', tone: 'curious' },
    { text: 'Nếu cậu nhìn lên sườn dốc, cậu thấy lối rẽ nào sáng nhất?', tone: 'curious' },
    { text: 'Hôm nay tớ cần một nhịp thở dài, cậu ngồi cạnh tớ nhé.', tone: 'moody' },
    { text: 'Cậu không cần vội; tớ sẽ giữ nhịp thật chậm cho cả đội.', tone: 'moody' },
    { text: 'Tớ nghe cậu rồi. Ta nghỉ một chút trước khi bước tiếp nhé.', tone: 'moody' },
    { text: 'Có lúc đường núi mờ sương; cậu cứ bình tĩnh, tớ vẫn ở đây.', tone: 'moody' },
    { text: 'Tớ hơi mệt ở đôi chân, nhưng lời động viên của cậu làm tớ ấm lòng.', tone: 'moody' },
    { text: 'Tớ vẫy cả hai tai rồi — cậu vừa tìm đúng lối thật tuyệt!', tone: 'joyful' },
    { text: 'Cả đội vui quá! Tớ muốn lăn một vòng trên bãi cỏ cùng cậu.', tone: 'joyful' },
    { text: 'Cậu tiến bộ từng bước, tớ nghe thấy niềm vui trong giọng cậu rồi!', tone: 'joyful' },
    { text: 'Tớ sẽ ghi ngày hôm nay vào sổ đường núi của chúng ta!', tone: 'joyful' },
    { text: 'Hoan hô cậu! Chiếc vòi tớ đang reo như kèn chiến thắng!', tone: 'joyful' },
    { text: 'Cậu đọc dấu hiệu thật kỹ; tớ sẽ giữ bản đồ phẳng và ngay ngắn.', tone: 'serious' },
    { text: 'Tớ nhắc cậu: kiên nhẫn giúp đôi mắt nhận ra lối đi an toàn.', tone: 'serious' },
    { text: 'Nếu chưa chắc, cậu dừng lại; tớ cùng cậu kiểm tra từng dấu.', tone: 'serious' },
    { text: 'Một đường đi tốt cần suy nghĩ vững vàng, cậu không phải chạy đua.', tone: 'serious' },
    { text: 'Tớ sẽ canh ba lô, còn cậu tập trung vào manh mối trước mắt.', tone: 'serious' },
  ],
  'owl-purple': [
    { text: 'Tớ thấy cậu đang tiến bộ qua từng chi tiết nhỏ rồi đấy.', tone: 'encouraging' },
    { text: 'Cậu cứ tin vào đôi mắt tinh anh của chính cậu, tớ sẽ soi cùng.', tone: 'encouraging' },
    { text: 'Tớ luôn ở trên cao để nhìn thấy nỗ lực của cậu.', tone: 'encouraging' },
    { text: 'Một câu hỏi hay của cậu có thể mở ra cả lối suy luận.', tone: 'encouraging' },
    { text: 'Cậu chưa tìm ra ngay cũng chẳng sao, tớ sẽ cùng cậu nhìn lại.', tone: 'encouraging' },
    { text: 'Tớ vừa nháy mắt với mái ngói kia — cậu có bắt gặp không?', tone: 'playful' },
    { text: 'Cậu đoán xem chiếc bóng nào đang giấu một manh mối nhé?', tone: 'playful' },
    { text: 'Tớ bay một vòng, còn cậu thử tìm chi tiết tinh nghịch nhất!', tone: 'playful' },
    { text: 'Nếu tớ xoay cánh thật nhanh, cậu có theo kịp không?', tone: 'playful' },
    { text: 'Cậu nghe chưa? Một câu hỏi nhỏ vừa gõ cửa trí tò mò của tớ.', tone: 'playful' },
    { text: 'Cậu nhìn kỹ góc nhỏ kia chưa, tớ thấy một dấu hiệu rất lạ.', tone: 'curious' },
    { text: 'Tớ tự hỏi lối phố này đã để lại điều gì cho cậu khám phá?', tone: 'curious' },
    { text: 'Nếu đổi góc nhìn, cậu sẽ nhận ra chi tiết nào trước tiên?', tone: 'curious' },
    { text: 'Tớ muốn biết vì sao dấu hiệu ấy lại nằm đúng chỗ đó.', tone: 'curious' },
    { text: 'Cậu có thể kể tớ nghe điều mắt cậu phát hiện trước không?', tone: 'curious' },
    { text: 'Đêm nay tớ hơi lặng, cậu cho tớ ngắm suy nghĩ của cậu một lúc nhé.', tone: 'moody' },
    { text: 'Cậu cứ chậm rãi; đôi khi câu trả lời cần một khoảng trời yên.', tone: 'moody' },
    { text: 'Tớ đang gom những mảnh suy nghĩ, cậu đợi tớ một nhịp nhé.', tone: 'moody' },
    { text: 'Có chi tiết làm cậu rối à? Tớ sẽ nhìn lại cùng cậu thật nhẹ nhàng.', tone: 'moody' },
    { text: 'Tớ không cần bay cao hôm nay, chỉ cần cậu ngồi cạnh là đủ.', tone: 'moody' },
    { text: 'Tớ thấy rồi! Ánh mắt cậu vừa bắt được manh mối tinh tế nhất!', tone: 'joyful' },
    { text: 'Cú đập cánh ăn mừng đây — cậu làm cả phố cổ bừng sáng rồi!', tone: 'joyful' },
    { text: 'Tớ muốn bay quanh cậu ba vòng vì câu trả lời quá thông minh!', tone: 'joyful' },
    { text: 'Cậu mở được một lối suy luận tuyệt đẹp, tớ vui quá!', tone: 'joyful' },
    { text: 'Hoan hô cậu! Tớ nghe tiếng những dấu chấm than trong đôi cánh rồi!', tone: 'joyful' },
    { text: 'Cậu hãy quan sát trước khi kết luận; tớ sẽ chờ cùng cậu.', tone: 'serious' },
    { text: 'Tớ nhắc cậu: một chi tiết nhỏ cũng đáng được kiểm chứng.', tone: 'serious' },
    { text: 'Nếu hai dấu hiệu khác nhau, cậu hãy đặt chúng cạnh nhau để so sánh.', tone: 'serious' },
    { text: 'Tớ sẽ giữ câu hỏi thật rõ, còn cậu lần theo từng manh mối.', tone: 'serious' },
    { text: 'Cậu không cần trả lời thật nhanh; suy luận cẩn thận mới là điều đáng quý.', tone: 'serious' },
  ],
  'dragon-jade': [
    { text: 'Tớ thấy ánh sáng trong mắt cậu rồi; cậu sẵn sàng mở lối mới!', tone: 'encouraging' },
    { text: 'Cậu cứ bước tới, tớ sẽ giữ ngọn đèn xanh soi đường.', tone: 'encouraging' },
    { text: 'Tớ tin lòng can đảm của cậu có thể làm bản đồ bừng sáng.', tone: 'encouraging' },
    { text: 'Mỗi nỗ lực của cậu đều thêm một vì sao vào kho hành trình.', tone: 'encouraging' },
    { text: 'Tớ ở đây để nhắc cậu: điều kỳ diệu bắt đầu từ một bước dũng cảm.', tone: 'encouraging' },
    { text: 'Cậu có muốn đua xem ai gọi được tia sáng đầu tiên không?', tone: 'playful' },
    { text: 'Tớ vừa thổi một vòng khói hình la bàn — cậu thấy chưa?', tone: 'playful' },
    { text: 'Cậu giữ bản đồ nhé, tớ sẽ làm tiếng trống mở màn!', tone: 'playful' },
    { text: 'Nếu kho bản đồ biết nhảy, tớ sẽ nhảy cùng cậu ngay bây giờ!', tone: 'playful' },
    { text: 'Tớ giấu một tia lấp lánh trong vảy, cậu tìm ra được không?', tone: 'playful' },
    { text: 'Tớ tự hỏi phía sau lối sáng kia, cậu muốn khám phá điều gì trước?', tone: 'curious' },
    { text: 'Cậu thấy màu nào trên bản đồ gọi trí tò mò của cậu nhất?', tone: 'curious' },
    { text: 'Tớ muốn biết chuyến đi này đã làm cậu bất ngờ ở khoảnh khắc nào.', tone: 'curious' },
    { text: 'Nếu mở thêm một cánh cửa, cậu sẽ mong thấy manh mối gì?', tone: 'curious' },
    { text: 'Cậu thử nhìn ánh sáng phản chiếu nhé, tớ nghĩ nó đang kể chuyện.', tone: 'curious' },
    { text: 'Hôm nay ngọn lửa trong tớ dịu lại, cậu nghỉ cùng tớ một nhịp nhé.', tone: 'moody' },
    { text: 'Cậu không cần mạnh mẽ mọi lúc; tớ sẽ giữ ánh sáng cho cậu.', tone: 'moody' },
    { text: 'Tớ đang lắng nghe sự im lặng, cậu cứ để ý nghĩ trôi thật chậm.', tone: 'moody' },
    { text: 'Có lúc kho báu cần được mở từ từ, tớ chờ cùng cậu.', tone: 'moody' },
    { text: 'Tớ hơi nhớ những chặng đường đã qua, nhưng cậu ở đây làm tớ ấm lòng.', tone: 'moody' },
    { text: 'Bùng sáng rồi! Cậu vừa làm cả kho bản đồ reo vang!', tone: 'joyful' },
    { text: 'Tớ muốn tung vảy lấp lánh lên trời vì cậu làm được rồi!', tone: 'joyful' },
    { text: 'Cậu mở thêm một lối đi, tớ tự hào muốn bay một vòng quanh cậu!', tone: 'joyful' },
    { text: 'Ánh sáng của cậu lan tới cả đội — tớ vui quá!', tone: 'joyful' },
    { text: 'Hoan hô cậu! Hành trình hôm nay có thêm một điều kỳ diệu!', tone: 'joyful' },
    { text: 'Cậu hãy giữ bản đồ ngay ngắn và kiểm tra hướng đi trước khi bước.', tone: 'serious' },
    { text: 'Tớ nhắc cậu: lòng can đảm luôn đi cùng sự cẩn thận.', tone: 'serious' },
    { text: 'Nếu lối sáng chưa rõ, cậu dừng lại để đọc dấu hiệu thật kỹ.', tone: 'serious' },
    { text: 'Tớ sẽ canh kho bản đồ, còn cậu suy nghĩ từng bước thật vững.', tone: 'serious' },
    { text: 'Cậu đi xa bằng trí tò mò, nhưng nhớ mang theo sự kiểm chứng.', tone: 'serious' },
  ],
} as const satisfies Readonly<Record<PetId, readonly PetHomeDialogue[]>>;

export const PET_HOME_DIALOGUES: readonly PetHomeDialogue[] = PET_HOME_DIALOGUES_BY_PET['fox-orange'];

export function pickPetHomeDialogue(
  petId: PetId,
  previousIndex = -1,
  randomValue = Math.random(),
): { index: number; dialogue: PetHomeDialogue } {
  const catalog = PET_HOME_DIALOGUES_BY_PET[petId];
  const safeRandom = Number.isFinite(randomValue) ? Math.min(Math.max(randomValue, 0), 0.999999) : 0;
  let index = Math.floor(safeRandom * catalog.length);
  if (index === previousIndex) index = (index + 1) % catalog.length;
  return { index, dialogue: catalog[index] };
}
